# Generated by Django 2.1.2 on 2018-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickdraw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='key_id',
        ),
        migrations.AddField(
            model_name='drawing',
            name='drawing',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='drawing',
            name='strokes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='countrycode',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='word',
            field=models.CharField(default='', max_length=20),
        ),
    ]
